import type { NextPage } from "next";
import Head from "next/head";
// import { trpc } from "../utils/trpc";
import { getSession, signIn, useSession } from "next-auth/react";
import { Context } from "../server/router/context";
import Nav from "../components/Nav";

const Home: NextPage = () => {
	const { data: session, status } = useSession();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="max-w-7xl mx-auto px-4 sm:px-6">
				{/* <div className="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10"></div> */}
				<Nav />
				<p>
					{session?.user
						? "Welcome, " + session?.user?.name
						: "Loading..."}
				</p>
			</div>
		</>
	);
};

export default Home;

export async function getServerSideProps(ctx: Context) {
	const session = await getSession({ req: ctx.req });
	console.log("from index: ", session);
	if (!session?.user) {
		return {
			redirect: {
				destination: "/signin",
				permenant: false,
			},
		};
	}
	return { props: {} };
}
